### ISSUE TITLE
Autoeat and proxing a real client

### ISSUE THREAD

**Issue by lupettohf** [DrMoraschi/AFKBot#10]
Mineflayer-auto-eat should be added to prevent starving, it's a plug and play patch so it's easy to add. Something really useful to add would be a proxy like interface to join the server anytime with the bot on (pausing it while logged in from the real client). I tried playing with this https://github.com/PrismarineJS/mineflayer/issues/315 but had no luck getting it to work, the client simply hangs on Logging in, it probably need more glue logic and it's not as simple as "client logs in" --> "forward raw packets". Any ideas?

**Comment by DrMoraschi** [comment]
I agree on adding mineflayer-autoeat, I'll start working on it. About the proxy, neither I could get it to work.

**Comment by lupettohf** [comment]
> I agree on adding mineflayer-autoeat, I'll start working on it. About the proxy, neither I could get it to work.
Made a pull request for that, just need settings. 
I will try to continue hacking on the proxy, it would be a very HQ feature. Maybe I could try to borrow some code from https://github.com/themoonisacheese/2bored2wait (i'm not a nodejs developer, my knowledge of it is very limited)

**Comment by DrMoraschi** [comment]
Yeah sorry I had to close your PR. Had to clean some other code.

**Comment by lupettohf** [comment]
> Yeah sorry I had to close your PR. Had to clean some other code. Wanted more flexibility to the auto-eat
By the way, I tested the bot both on macOS and linux (raspbian), works with no issues.

**Comment by DrMoraschi** [comment]
New release with feature added, I'll leave this open so you can post updates on your proxy project if you like.

**Comment by lupettohf** [comment]
> New release with feature added, I'll leave this open so you can post updates on your proxy project if you like.

I managed to get a semi working proxy using code borrowed from 2bored2wait, had no luck to get mineflayer to work since it lacks the on 'packet' event. One approach would be to make the server listen on start, if no player is connected starts the mineflayer client, upon player connection quits mineflayer and the bot and starts a normal mc client and forwards the connection.

**Comment by lupettohf** [comment]
> > New release with feature added, I'll leave this open so you can post updates on your proxy project if you like.
> 
> I managed to get a semi working proxy using code borrowed from 2bored2wait, had no luck to get mineflayer to work since it lacks the on 'packet' event. One approach would be to make the server listen on start, if no player is connected starts the mineflayer client, upon player connection quits mineflayer and the bot and starts a normal mc client and forwards the connection.

Update, i can just access the raw client using bot._client.on('packet'... i have an ingame working proxy now. Time to glue the other stuff

**Comment by lupettohf** [comment]
Turns out it's not that simple since mineflayer implemets a full client, some solutions requires workarounds that are version dependant so I made a different project since I just need this to work on 1.12.2 lupettohf/neobot

**Comment by DrMoraschi** [comment]
Cool!

**Comment by DrMoraschi** [comment]
I'll close this as your neobot project hasn't been updated in the las 2 weeks. Feel free to reopen :)
