### ISSUE TITLE
Type Error: Cannot Read property 'send

### ISSUE THREAD

**Issue by Aadvik-Ranjan** [DrMoraschi/AFKBot#17]
I was trying to install the afk bot, i installed all the dependencies and stuff and set up the bot , but when i run the node index.js it just shows the error

**Comment by DrMoraschi** [comment]
Can you fill the issue template? Give more information? Maybe attach your config.json censoring your credentials?

**Comment by Aadvik-Ranjan** [comment]
How do i hide the credentials just remove them?

**Comment by DrMoraschi** [comment]
Yes

**Comment by Aadvik-Ranjan** [comment]
here it is :

{
    "server" : {
        "host" : "",
        "port" : 25554
    },

    "botOptions" : {
        "username" : "AFKBot",
        "password" : "",
        "authMethod" : "mojang",
        "msgToWhisper" : "Sorry, I'm an AFK Bot"
    },

    "announcements" : {
        "saySomething" : {
            "enable" : false,
            "interval" : 10000,
            "lineToSay" : "No"
        },

        "windowsAnnouncements" : true,

        "discordBot": {
            "sendChat" : true,
            "token" :"",
            "channelID" : "",
            "sayEverything" : true,
            "prefix" : "+",
            "embedHexColor" : "#0001ff",
            "userIDToPing" :""
        }
    },
    
    "misc" : {
        "owner" : "",
        "attackMobs" : true,
        "lookAtEntities" : false	,
        "reconnectOnKick" : true,

        "autoEat" : {
            "startAt" : 10,
            "priority" : "foodPoints"
        }
    },

    "timeouts" : {
        "onKicked" : 10000,
        "antiAFK" : 600000
    }
}
