### ISSUE TITLE
[BUG] Bot cannot follow players in nether

### ISSUE THREAD

**Issue by ZunDubCore** [DrMoraschi/AFKBot#20]
**Describe the bug**
When being in nether, `+follow username` does not work. The bot cannot move.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v15.8.0
 - Minecraft version: 1.16.5

**Comment by DrMoraschi** [comment]
Hmm, works for me. Cannot reproduce

**Comment by ZunDubCore** [comment]
@DrMoraschi Everything works fine if the bot enters into a nether portal. However, the bot can't follow me when it spawns directly in the nether dimension. In this case, `prismarine-viewer` doesn't work neither, it crashes with the following error:

```
[...]\AFKBot\src\Viewer.js:32
            const blockPos = block.position.offset(0, 1, 0);
                                   ^

TypeError: Cannot read property 'position' of null
    at EventEmitter.<anonymous> ([...]\AFKBot\src\Viewer.js:32:36)
    at EventEmitter.emit (node:events:378:20)
    at WorldView.<anonymous> ([...]\AFKBot\node_modules\prismarine-viewer\lib\mineflayer.js:49:18)
    at WorldView.emit (node:events:378:20)
    at Socket.<anonymous> ([...]\AFKBot\node_modules\prismarine-viewer\viewer\lib\worldView.js:38:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by ZunDubCore** [comment]
@DrMoraschi The problem only appears when bot spawns directly in nether dimension on login. When it enters a nether portal, everything works as expected.

**Comment by DrMoraschi** [comment]
Still can't reproduce it :(

https://i.imgur.com/PnCzFqF.mp4

**Comment by ZunDubCore** [comment]
@DrMoraschi Sometimes it works correctly, but most of the time I am still getting this error sadly.

**Comment by DrMoraschi** [comment]
Are you sure there aren't plugins messing something?

**Comment by ZunDubCore** [comment]
@DrMoraschi What plugins? On server side?

**Comment by DrMoraschi** [comment]
Yup

**Comment by ZunDubCore** [comment]
@DrMoraschi Actually, I tried on vanilla server and everything works fine

**Comment by ZunDubCore** [comment]
So, the problem is because of plugins?

**Comment by DrMoraschi** [comment]
Seems like it. I tried it on a spigot server, but with only WorldEdit installed, so honestly I don't know

**Comment by ZunDubCore** [comment]
@DrMoraschi It works my paper server, but doesn't work on another paper server with more plugins :(

**Comment by DrMoraschi** [comment]
Hmm, then I think it's definitely some plugin messing with the dimensions

**Comment by ZunDubCore** [comment]
@ZunDubCore Same thing happens in overworld :(
