### ISSUE TITLE
walking

### ISSUE THREAD

**Issue by josephisticated** [DrMoraschi/AFKBot#23]

**Comment by DrMoraschi** [comment]
I could implement a randomizer of movements, but if you want to make it walk just somewhere, you have the viewer, you can click a block and it will pathfind to it

**Comment by josephisticated** [comment]
I'm clicking on prismarine viewer but it doesn't go anywhere

**Comment by DrMoraschi** [comment]
Any errors on the console or discord?

**Comment by josephisticated** [comment]
no theres no error, but people in server say that the bot is moving its head around

**Comment by DrMoraschi** [comment]
Hm did you try with the middle button of the mouse on the viewer? Also can you try to follow a player or go to a coord?

**Comment by josephisticated** [comment]
oh sorry didn't know about the middle button,
are there any other control buttons? because prismarine viewer's left click-right click moving around isn't convenient

**Comment by DrMoraschi** [comment]
Hmm, as of right now, I think prismarine-viewer doesn't have the ability to change the buttons. I will ask

**Comment by josephisticated** [comment]
and by the way is there a way to import Minecraft chat directly into the discord chat so people in the discord server can chat with people in mc

**Comment by DrMoraschi** [comment]
Yes you can, enable both send-chat-to-minecraft(discord options) and send-chat-to-ds(misc-options).
It appears you can do it but the process is a bit complicated for me.

I'll keep this open until I add a movement randomizer

**Comment by josephisticated** [comment]
alright, thanks a lot ^-^

**Comment by josephisticated** [comment]
![image](https://user-images.githubusercontent.com/53388005/109350819-3893e000-7889-11eb-83b2-15fc8c7c8b27.png)
dont know why but this happened and its still texting this, in game no one's texting something like this

**Comment by DrMoraschi** [comment]
That's the bot? Did you make it say something?

**Comment by josephisticated** [comment]
no, started getting these out of nowhere

**Comment by DrMoraschi** [comment]
So is it the bot or not?

Can you send the log? It should be the log with the greatest number

**Comment by josephisticated** [comment]
couldnt find it in any logs, i will send if this happens again and I could find the file

**Comment by DrMoraschi** [comment]
It should be in the logs folder

**Comment by josephisticated** [comment]
i checked all of the logs but there were lots of chatting missing, or are you looking for errors?

**Comment by DrMoraschi** [comment]
Everything, if you could send the log

**Comment by josephisticated** [comment]
[log10.log](https://github.com/DrMoraschi/AFKBot/files/6052415/log10.log)

**Comment by DrMoraschi** [comment]
Looks like you had some problems, did you fill all the discord channel ids and server ids?

**Comment by josephisticated** [comment]
yes and im using it without any problems except that red squares

**Comment by DrMoraschi** [comment]
How does the message look in minecraft? Or in discord? Those look like special characters

**Comment by josephisticated** [comment]
there isnt anything in mc, but the discord bot keeps spamming these
![image](https://user-images.githubusercontent.com/53388005/109354174-734c4700-788e-11eb-8f5a-8a775cc0f16e.png)

**Comment by DrMoraschi** [comment]
Did this happen before enabling send-chat-to-minecraft(discord options) and send-chat-to-ds(misc-options)?
I don't know what happened, the bot shouldn't be sending random messages, or maybe you enabled it in the config somewhere, as AFKBot has a function to send a message every x seconds, even tho it's off by default

**Comment by josephisticated** [comment]
I didn't even change the discord RPC etc. so I'm not the one who triggered it but it's probably server-sided

**Comment by DrMoraschi** [comment]
That's very strange, i'll test it if it happens on my server

**Comment by josephisticated** [comment]
this server has some unnecessary plugins that cleans chat or turning <3 into unicode heart etc. so they might be the problem

**Comment by DrMoraschi** [comment]
Yeah that's probably it, thanks for telling me

**Comment by josephisticated** [comment]
yes, the one who spammed hearts in the discord chat is the bot
it was spamming those because it seemed like someone was spamming hearts in the mc chat but no one is sending hearts in the chat

and the viewer works just fine over the server, i just wanted to change the message that the bot sends you when you type +start

**Comment by josephisticated** [comment]
![image](https://user-images.githubusercontent.com/53388005/109464788-48254b80-7a78-11eb-99cf-6981bfabd067.png)
crashes when using prismarine, not immediately but always happen at the end

**Comment by josephisticated** [comment]
![image](https://user-images.githubusercontent.com/53388005/109465450-414b0880-7a79-11eb-9286-a354e4a83701.png)

**Comment by josephisticated** [comment]
found the thing with the hearts, this server has a plugin that shows how much hp the person you're looking at
![image](https://user-images.githubusercontent.com/53388005/109620604-1f21bb00-7b4b-11eb-9b46-3ddc274c3abc.png)
this can be eliminated if you can make the bot look away from people

**Comment by DrMoraschi** [comment]
No need to close it, issue is still not fixed. I will close it on the next release

**Comment by DrMoraschi** [comment]
Thanks for removing the comments, now I can't see where the bot crashed and I can't solve the issues :)

**Comment by josephisticated** [comment]
actaully there wasnt a problem, it was actually caused by me, i was running this on a google cloud ubuntu machine, and didnt use the 'tmux' command, and the hearts were caused by a server plugin that prints out the players hp on top of your toolbar. ive been using the bot for a pretty long time now and im just having some minor crashes, sometimes because of prismarine and other bot assets and sometimes server resets etc. i can still send crash reports if you want to

**Comment by DrMoraschi** [comment]
I still needed the comments to fix the little crashed, but allright

**Comment by josephisticated** [comment]
sorry i thought it was kinda unnecessary because of not being able to contact you :/

**Comment by DrMoraschi** [comment]
You could have joined the Discord server if you had Discord

**Comment by josephisticated** [comment]
what discord server 😳

**Comment by DrMoraschi** [comment]
First thing in the readme

**Comment by josephisticated** [comment]
i am genuinely sorry, ive never noticed it until now
