### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by HemangKeswani12** [DrMoraschi/AFKBot#24]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HemangKeswani12** [comment]
can u dm me in discord showing me how to use this?kay.#1073

**Comment by DrMoraschi** [comment]
1. Please fill the Issue
2. Please read the instructions before creating a new issue
3. Join our Discord for this kind of help
4. Don't post your discord, privacy issues.
