### ISSUE TITLE
Heroku support?

### ISSUE THREAD

**Issue by ImGlitchh** [DrMoraschi/AFKBot#25]
so, I tried using heroku so I didnt have to keep my pc online 24/7, and apprently it's not working because heroku already sets an ip for the app(or at least from what I found on google I have never coded in my life) 
So it gives me this error:

Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
Stopping process with SIGKILL
Process exited with status 137
State changed from starting to crashed

Is there any way you can fix this?

**Comment by DrMoraschi** [comment]
SHORT ANSWER: No

LONG ANSWER: No, sorry. I have done this before and I deleted the Repository of AFKBot-Heroku out of frustration. This thing is meant to run on a local computer. Before the v2 update it was easier. But now it's more complicated. Sorry but I don't plan on offer support on this.
