### ISSUE TITLE
I was able to make it work with heroku.

### ISSUE THREAD

**Issue by ImGlitchh** [DrMoraschi/AFKBot#26]
So, I kinda just put this line in the index.js file:

port = process.env.PORT || *my port*;

And it has been working, I just wanted to tell you since you could tell people that want to use heroku.

It has been online for the last 20 minutes, I will give you an update if something happens.

**Comment by ImGlitchh** [comment]
sorry if I annoyed you by putting this into request, just wanted to inform you.

**Comment by DrMoraschi** [comment]
No problem, I actually didn't think of that.
Thanks for telling me

**Comment by ImGlitchh** [comment]
No problemo
