### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Guest0070** [DrMoraschi/AFKBot#28]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS [e.g. Windows]: Windows 10
 - Node version [e.g. 12.18.3]:v14.15.4
 - Minecraft version [e.g. 1.16.1]: 1.16.5

**Expected behavior**
ERROR INITIALIZING: TypeError: Cannot read property 'members' of undefined
**Screenshots**
https://ibb.co/RSMFYYF
**Additional context**
whenever I run `index.js` that happens

**Comment by DrMoraschi** [comment]
This is caused because either the bot hasn't joined the server or the guild ID is incorrect

**Comment by DrMoraschi** [comment]
Reopen if issue is not solved
