### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by josephisticated** [DrMoraschi/AFKBot#32]
**Is your feature request related to a problem? Please describe.**
it takes really long to place blocks for leveling up in skyblock

**Describe the solution you'd like**
mineflayer is able to place blocks, so itd be nice to make the bot place blocks to fill somewhere, like it'll ask 2 coordinates, 1 as starting 2 as ending point, it will fill all the place between these two points with the block/s you specify

**Describe alternatives you've considered**
make the bot print schematic files legitimately

**Additional context**

**Comment by DrMoraschi** [comment]
This is out of scope for an *AFK* bot
