### ISSUE TITLE
i cant get the bot to work

### ISSUE THREAD

**Issue by SpoolySnail** [DrMoraschi/AFKBot#34]
im new to this so please excuse me if i am a dumbass , i cannot get the bot to join a minecraft server, on startup it connects to the discord bot and server , but it wont connect to any server because i keep getting the error: TypeError: Cannot read property 'username' of undefined i only deleted the part where the name said AFKBot and inserted my minecraft username, the server i am trying to join is in 1.16.5 and my platform is windows thx in advance

**Comment by DrMoraschi** [comment]
Could you send your config.json and log? You can delete the token and the password of the account

**Comment by SpoolySnail** [comment]
[AFKBot.zip](https://github.com/DrMoraschi/AFKBot/files/6222378/AFKBot.zip)

**Comment by SpoolySnail** [comment]
also i am using carcked mincraft so the account doesn't have a password

**Comment by DrMoraschi** [comment]
Ok I see the problem, you replaced the entire property of "afkbot", you don't have to change that, just change the username and password in that property. For example:

![Image](https://i.imgur.com/p6mR10s.png?1.png)

**Comment by SpoolySnail** [comment]
ok i will try it like that thnak you ,also if its a cracked account what do i do with the authorisation method, do i leave mojang, leave it blank or something else?

**Comment by DrMoraschi** [comment]
You can leave the authentication field as it is, as you are using a cracked account, there is nothing to authenticate.
For the password field, you can leave it as it is also.

**Comment by SpoolySnail** [comment]
![image](https://user-images.githubusercontent.com/81561594/112856866-88481000-90b0-11eb-8b72-9eaab908c4cc.png)
i am still getting the same error , it is written the same way as in your screenshot

**Comment by SpoolySnail** [comment]
![image](https://user-images.githubusercontent.com/81561594/112857036-baf20880-90b0-11eb-990a-18dc305ec4a9.png)

**Comment by DrMoraschi** [comment]
Did you start the bot before doing the Status command?

**Comment by SpoolySnail** [comment]
yes of course

**Comment by DrMoraschi** [comment]
Does the bot work apart from that error?

**Comment by DrMoraschi** [comment]
You are getting that error when executing Status. What happens when you execute Start?

**Comment by sstr1ke** [comment]
i kinda have same issue

**Comment by SpoolySnail** [comment]
when i execute start in discord nothing happens
i have to start the bot in command prompt

**Comment by DrMoraschi** [comment]
Can you join the Discord Server? And what do you mean by starting the bot from the command prompt, you mean the entire bot?

**Comment by SpoolySnail** [comment]
Hey so my friend got it to work and sent me his config file, everything works now

**Comment by SpoolySnail** [comment]
Thanks for your help

**Comment by DrMoraschi** [comment]
Alright, sorry for not being helpful.

**Comment by sstr1ke** [comment]
u were helpful i double checked everything and it worked
