### ISSUE TITLE
[BUG] constant write EPIPE error when using +goto

### ISSUE THREAD

**Issue by Lemon553311-dev** [DrMoraschi/AFKBot#36]
**Describe the bug**
constantly getting write EPIPE error when using +goto command (far coords)

**Desktop (please complete the following information):**
 - OS [e.g. Windows]: linux
 - Node version: 15.13.0
 - Minecraft version: 1.16.5

**Expected behavior**
bot actually going to the far coords

**Screenshots**

**Additional context**
bot stops after 15 seconds~

**Comment by DrMoraschi** [comment]
I think that means something is trying to use the bot when it's disconnected. Can you try with shorter distances?

**Comment by Lemon553311-dev** [comment]
Shorter distances work perfectly fine but NOW instead of throwing epipe the bot goes to random coordinates??
Like if I do +goto 2471 63 -245 the bot just goes to: x: -33 y: 65 z: -247

I tried restarting the bot, still doesnt work

**Comment by DrMoraschi** [comment]
I'm still trying to find out. Does the bot get kicked from the server?

**Comment by Lemon553311-dev** [comment]
I assume he got kicked out + this is an EPIPE error
![image](https://user-images.githubusercontent.com/60439353/113471253-f8191a80-9463-11eb-8a24-b43195a987e0.png)

**Comment by Lemon553311-dev** [comment]
This might sound really confusing but I found out that bot leave on write EPIPE error when:

1. far coords on +goto
**2. do +status command after 30s-1m~**
3. watch it think for a long time and throw EPIPE and time out

**after epipe error you still can do that status command successfully while the bot got disconnected for some reason**

**Comment by DrMoraschi** [comment]
Could you share your log and your config.json (removing the Token)?

**Comment by Lemon553311-dev** [comment]
log: https://pastebin.com/vy5p145B
config: https://pastebin.com/tJy6qXg9 (no = private)

**Comment by DrMoraschi** [comment]
Hi, I cannot reproduce this. This could be caused because the server is laggy. I also cannot reproduce the long range goal. I've read some issues about the `handleDisconnection()` and it seems a server side issue. So that kicks the bot, and because the bot is still sending information to the server, it will crash.

**Comment by DrMoraschi** [comment]
Are you still having this issue?

**Comment by DrMoraschi** [comment]
Reopen if needed
