### ISSUE TITLE
[BUG] Doesnt load nearby chunks thus pathfinding breaks

### ISSUE THREAD

**Issue by BlueGuitarCL** [DrMoraschi/AFKBot#39]
After logging in for the first time, the bot doesnt recognizes the chunk its standing on. (Noticeable cause `+goto` or `+follow` tries to work but no movement, and void chunks appears on prismarine webserver)

System Info:
 - OS: Manjaro Gnome (Desktop)
 - Node version:16.0.0
 - Minecraft version: 1.16.5

**Expected behavior**
The bot should always recognize nearby chunks for pathfinding and display on prismarine server.

**Screenshots**
![Prismarine unresponsive](https://user-images.githubusercontent.com/23057858/116587540-8f00b780-a8e8-11eb-9909-f8393daf9823.jpg)

![Trying antiafk path unsuccesfully](https://user-images.githubusercontent.com/23057858/116588141-2e25af00-a8e9-11eb-86f4-6b94508c3c03.jpg)

![Unloaded chunks, red line on the middle is the bot path](https://user-images.githubusercontent.com/23057858/116589490-b193d000-a8ea-11eb-99cf-751ce6a738b4.jpg)

Workaround: Killing the bot and let it respawn. Problem fixed until `+leave` or `+exit` is invoked.

Note: I noticed that the bot is unresponsive too when in the prismarine view the camera its outside the default 6 loaded chunks. On that state prismarine doesnt catch any input.

Off-topic: Could you add a feature to fixed anti-afk movement or toggles for breaking placing jumping etc?  Just tried the bot yesterday and today just when i woke up i restarted the bot with the workaround and after a moment a phantom killed it and i didnt noticed lol. Ig it picked a different path and when it made a hole and standed outside it got killed

**Comment by DrMoraschi** [comment]
Hi, could you send the Log? You can find it inside the /logs/ folder.

**Comment by BlueGuitarCL** [comment]
Sure, heres the state of the bot when retrieved the log:
![Screenshot_2021-04-29-13-15-38-016_com brave browser](https://user-images.githubusercontent.com/23057858/116592296-db022b00-a8ed-11eb-84b0-88ada3c917d6.jpg)
[log0.log](https://github.com/DrMoraschi/AFKBot/files/6400475/log0.log)

And, i just noticed that there are some particles showing its trying to move.
![2021-04-29_13 14 58](https://user-images.githubusercontent.com/23057858/116592526-1ac91280-a8ee-11eb-8d9d-cc8b6c562fb9.png)

**Comment by DrMoraschi** [comment]
Strange Issue indeed, logs look fine, can you provide me steps to reprduce this error? Or is it just when it spawns?

**Comment by BlueGuitarCL** [comment]
Straight forward its just on spawn. As i mentioned when i `npm install` the zip contents and execute it for the first time it works flawlessly. But after the first disconnection issues begin.
