### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mustafa383** [DrMoraschi/AFKBot#42]
**Describe the bug**
+say command not working

**Desktop (please complete the following information):**
 - OS : Windows
 - Node version [e.g. 12.18.3]: latest version
 - Minecraft version [e.g. 1.16.1]: 1.15.2

**Expected behavior**
 Sending messages into the game chat

**Comment by DrMoraschi** [comment]
Can you paste the log?

**Comment by mustafa383** [comment]
This command does not exist, so it is not logged

**Comment by DrMoraschi** [comment]
Are you sure? Can you send screenshot of the message in discord when the bot starts?

**Comment by mustafa383** [comment]
It's in the message there. but it doesn't work.

**Comment by DrMoraschi** [comment]
What do you mean it doesn't work, does it connect to discord?

**Comment by mustafa383** [comment]
src/modules/DiscordModules.js you can review the file

**Comment by DrMoraschi** [comment]
You need to send me your log, located in the /logs/ folder, assuming you're using the latest version

**Comment by mustafa383** [comment]
![Screenshot_279](https://user-images.githubusercontent.com/57295889/123835241-fc44bf00-d910-11eb-9c70-f36b8dad3486.png)

**Comment by mustafa383** [comment]
No module for say command

**Comment by DrMoraschi** [comment]
Did you start the bot before using that command?

**Comment by mustafa383** [comment]
yes

**Comment by DrMoraschi** [comment]
What's your config.json?

**Comment by mustafa383** [comment]
![Screenshot_280](https://user-images.githubusercontent.com/57295889/123835657-7d03bb00-d911-11eb-9c5e-da3b61c5d19d.png)

**Comment by DrMoraschi** [comment]
When enabling "send-chat-to-minecraft", the Say command gets disabled automatically

**Comment by mustafa383** [comment]
Thanks for the help.
