### ISSUE TITLE
[Bug] Webhook

### ISSUE THREAD

**Issue by MrHakan** [DrMoraschi/AFKBot#6]
when webhook is true it crashes
//////////////////////////////////////
when webhook is false its send player list and when bot dies it sends playerlist again

**Comment by DrMoraschi** [comment]
Already saw your message in discord but thank you anyways :)

**Comment by DrMoraschi** [comment]
Mineflayer doesn't support 1.16.4. I've solved the other issues, and added so you have to fill in the Minecraft version in the Bug Report. Please fill the Bug Report from now on or I'll have to close the issue.
