### ISSUE TITLE
the ability to join modded server

### ISSUE THREAD

**Issue by Wendys-corp** [DrMoraschi/AFKBot#9]
**Is your feature request related to a problem? Please describe.** 
if anything i would like it to be able to join my modded forge server
**Describe the solution you'd like**
the ability to have the bot load mods like forge so it can join the server
**Describe alternatives you've considered**
or some kind of bypass so you don't have to load mods

**Additional context**
the bot supports modded worlds as well

**Comment by DrMoraschi** [comment]
Mineflayer currently doesn't support Forge mods as they're made with Java, and mineflayer uses Node Javascript.

**Comment by Wendys-corp** [comment]
> Mineflayer currently doesn't support Forge mods as they're made with Java, and mineflayer uses Node Javascript.

umm so do you have any alternatives that i can use

**Comment by DrMoraschi** [comment]
Maybe there are some Forge mods that create a fake player, I haven't investigated.

**Comment by Wendys-corp** [comment]
> Maybe there are some Forge mods that create a fake player, I haven't investigated.

the server that im on has offline mode set to false and kicks idle players so um trying to find something that will move my player every 5 minutes or so

**Comment by DrMoraschi** [comment]
If you don't mind leaving your minecraft open, there are many programs that send a specific key input. Like AHK or MacroRecorder. MacroRecorder asks you to pay after ten loops though.

**Comment by Wendys-corp** [comment]
one more thing how do i know if the bots running and how do i stop it if it is running

**Comment by DrMoraschi** [comment]
If you've started the bot correctly, there should be an overlay like [this](https://github.com/wvffle/mineflayer-dashboard/blob/master/docs/screenshot.png) in your terminal. To stop the bot, you press Control + C

**Comment by Wendys-corp** [comment]
> If you've started the bot correctly, there should be an overlay like [this](https://github.com/wvffle/mineflayer-dashboard/blob/master/docs/screenshot.png) in your terminal. To stop the bot, you press Control + C

i used command prompt to start it and i dont have that

**Comment by DrMoraschi** [comment]
Works for me, can you join the discord server? It's easier if we talk there.

https://discord.com/invite/JQeVxbQT5G
